//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.FlightDocs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.FlightDocs.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_AdditionalInfo_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_AdditionalInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport code.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_AirportCode_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_AirportCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_Altitude_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_Altitude_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_CompanyName_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_CompanyName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight date.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_FlightDate_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_FlightDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight time.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_FlightTime_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_FlightTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_GenerateText_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_GenerateText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max altitude.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_MaxAlt_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_MaxAlt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min altitude.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_MinAlt_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_MinAlt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg numbers.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_RegNumbers_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_RegNumbers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_SaveToCfg_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_SaveToCfg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_StartTime_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_StartTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAV count.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_UavCount_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_UavCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAV operator.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_UavOperatorName_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_UavOperatorName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR MR number.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetView_VrMrNumber_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetView_VrMrNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Plan Text Generator.
        /// </summary>
        public static string FlightPlanGeneratorMapWidgetViewModel_Title {
            get {
                return ResourceManager.GetString("FlightPlanGeneratorMapWidgetViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string FlightPlanViewModel_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FlightPlanViewModel_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight plan.
        /// </summary>
        public static string FlightPlanViewModel_Title {
            get {
                return ResourceManager.GetString("FlightPlanViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Points.
        /// </summary>
        public static string FlightZoneActionViewModel_SelectPoint_Title {
            get {
                return ResourceManager.GetString("FlightZoneActionViewModel_SelectPoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string FlightZoneAnchor_Name {
            get {
                return ResourceManager.GetString("FlightZoneAnchor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string FlightZoneMapWidgetView_Altitude_Title {
            get {
                return ResourceManager.GetString("FlightZoneMapWidgetView_Altitude_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string FlightZoneMapWidgetView_Latitude_Title {
            get {
                return ResourceManager.GetString("FlightZoneMapWidgetView_Latitude_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string FlightZoneMapWidgetView_Longitude_Title {
            get {
                return ResourceManager.GetString("FlightZoneMapWidgetView_Longitude_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FlightZoneMapWidgetView_Name_Title {
            get {
                return ResourceManager.GetString("FlightZoneMapWidgetView_Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string FlightZoneMapWidgetView_Remove_Title {
            get {
                return ResourceManager.GetString("FlightZoneMapWidgetView_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Zone Points Editor.
        /// </summary>
        public static string FlightZoneMapWidgetViewModel_Title {
            get {
                return ResourceManager.GetString("FlightZoneMapWidgetViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Zone.
        /// </summary>
        public static string HeaderFlightDocsMenuItem_Title {
            get {
                return ResourceManager.GetString("HeaderFlightDocsMenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select landing point.
        /// </summary>
        public static string TakeOffLandActionViewModel_SelectLandPoint_Title {
            get {
                return ResourceManager.GetString("TakeOffLandActionViewModel_SelectLandPoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select take off point.
        /// </summary>
        public static string TakeOffLandActionViewModel_SelectTakeOffPoint_Title {
            get {
                return ResourceManager.GetString("TakeOffLandActionViewModel_SelectTakeOffPoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string TakeOffLandAnchor_Name {
            get {
                return ResourceManager.GetString("TakeOffLandAnchor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Off and Land Points Editor.
        /// </summary>
        public static string TakeOffLandMapWidgetViewModel_Title {
            get {
                return ResourceManager.GetString("TakeOffLandMapWidgetViewModel_Title", resourceCulture);
            }
        }
    }
}
